---
title: 异常基础
date: 2020-03-07 18:25:08
tags:
	- 异常
	- Java
categories: 学习
---

#### 简述

在程序中出现的错误（无论是编译时还是运行时出现的），称为异常(Exception)。Java使用一种称为异常处理的错误捕获机制来处理这些异常。

和Java 的其他任何对象一样，异常需要用new在内存堆里创建实例。在所有标准异常中， 存在着两个构建器：第一个是默认构建器，第二个则需使用一个字串自变量，使我们能在异常里置入相关信息：

`new RuntimeException("Null Exception")`

其中的字符串可用各种方法提取出来。

关键字throw会首先执行new表达式，创建一个不在程序常规执行范围之内的对象。随后，对象实例会从方法中返回。通过抛出一个异常，就可以从原来的作用域中退出。

<!--more-->

+ 异常的分类

![异常的分类](https://i.loli.net/2020/03/15/J4kdx3URuL12wos.png)

Java标准库内建了一些通用的异常，这些类以Throwable为顶层父类。Throwable又派生出Error类和Exception类。

Java语言规范将派生于Error类或RuntimeException类的所有异常称为非受查(unchecked)异常，所有其他的异常称为受查(checked)异常。

#### 捕获异常

针对想捕获的每种异常类型，都必须有一个相应的异常控制器。异常控制器紧接在try块后面，且用catch关键字标记。格式如下所示：

```java
try {
    ... 
} catch(Type1 e) { 
    ... 
} catch(Type2 e) { 
    ... 
} catch(Type3 e) { 
    ... 
}... 
```

控制器必须“紧接”在try块后面，若抛出一个异常，违例控制机制就会搜寻自变量与异常类型相符的第一个控制器。随后，它会进入那个catch从句，并认为异常已得到控制。只有相符的catch从句才会得到执行，它与switch语句不同，后者在每个case后都需要一个break命令，防止误执行其他语句。

通常情况下，可以使用`catch(Exception e) { }`作为可选控制器的最后一个控制器，因为Exception是所有受查异常的超类，所以捕获Exception异常可以避免捕获失败而导致异常被抛出使程序中断。

#### 自定义异常

有的时候现有的异常并不能够满足我们的需求，这时候就可以自定义一个异常。自定义的异常类需要继承Exception类。

```java
class MyException extends Exception {
    private int i;
    public int val() { return i; }
    public MyException() {}
    public MyException(String msg) {
        super(msg);
    }
    public MyException(String msg, int x) {
        super(msg);
        i = x;
    }
}
public class Inheriting {
    public static void f() throws MyException {
        System.out.println("Throwing MyException from f()");
        throw new MyException();
    }
    public static void g() throws MyException {
        System.out.println("Throwing MyException from g()");
        throw new MyException("Originated in g()");
    }
    public static void h() throws MyException {
        System.out.println("Throwing MyException from h()");
        throw new MyException("Originated in h()", 47);
    }
    public static void main(String[] args) {
        try {
            f();
        } catch(MyException e) {
            e.printStackTrace();
        }
        try {
            g();
        } catch(MyException e) {
            e.printStackTrace();
        }
        try {
            h();
        } catch(MyException e) {
            e.printStackTrace();
            System.out.println("e.val() = " + e.val());
        }
    }
}
```



#### 声明异常

对于一般的非受查异常，所有代码都具有抛出这些异常的能力，而对于受查异常，我们必须要在方法中声明所有可能抛出的异常，来提示使用方法的人可能会出现的异常，例如：

`public void f(String s) throws FileNotFoundException, EOFException { }`

另外，如果在子类中覆盖了超类的一个方法，子类方法中声明的受查异常不能比超类方法中声明的异常更通用（也就是说，子类方法中可以抛出更特定的异常，或者根本不抛出任何异常）。并且，如果超类方法没有抛出任何异常，子类也不能抛出任何受查异常。

```java
class BaseballException extends Exception {}

class Foul extends BaseballException {}

class Strike extends BaseballException {}

abstract class Inning {
    Inning() throws BaseballException {}
    void event () throws BaseballException {
        // Doesn't actually have to throw anything
    }
    abstract void atBat() throws Strike, Foul;
    void walk() {} // Throws nothing
}

class StormException extends Exception {}

class RainedOut extends StormException {}

class PopFoul extends Foul {}

interface Storm {
    void event() throws RainedOut;
    void rainHard() throws RainedOut;
}

public class StormyInning extends Inning implements Storm {
    // OK to add new exceptions for constructors, but you must deal with the base constructor exceptions:
    StormyInning() throws RainedOut,BaseballException {}
    StormyInning(String s) throws Foul,BaseballException {}
    
    // Regular methods must conform to base class:
    //!void walk() throws PopFoul {} //Compile error
    
    // Interface CANNOT add exceptions to existing methods from the base class:
    //! public void event() throws RainedOut {}
    
    // If the method doesn't already exist in the base class, the exception is OK:
    public void rainHard() throws RainedOut {}
    
    // You can choose to not throw any exceptions, even if base version does:
    public void event() {}
    
    // Overridden methods can throw inherited exceptions:
    void atBat() throws PopFoul {}
    
    public static void main(String[] args) {
        try {
            StormyInning si = new StormyInning();
            si.atBat();
        } catch(PopFoul e) {
        } catch(RainedOut e) {
        } catch(BaseballException e) {}
        // Strike not thrown in derived version.
        
        try {
            // What happens if you upcast?
            Inning i = new StormyInning();
            i.atBat();
            // You must catch the exceptions from the base-class version of the method:
        } catch(Strike e) {
 		} catch(Foul e) {
 		} catch(RainedOut e) {
 		} catch(BaseballException e) {}
 	}
}
```

#### Finally

无论一个异常是否在try 块中发生，我们经常都想执行一些特定的代码。为达到这个目的，可在所有异常控制器的末尾使用一个finally从句。所以完整的异常控制小节可以像下面这个样子： 

```java
try {
    ...
} catch (A a1) { 
    ...
} catch (B b1) { 
    ...
} catch (C c1) { 
    ...
} finally {
    ...
}
```

举个例子：

```java
public class FinallyWorks {
    static int count = 0;
    public static void main(String[] args) {
        while(true) {
            try {
                // post-increment is zero first time:
                if(count++ == 0)
                    throw new Exception();
                System.out.println("No exception");
            } catch(Exception e) {
                System.out.println("Exception thrown");
            } finally {
                System.out.println("in finally clause");
                if(count == 2) break; // out of "while"
            }
        }
    }
} 
```

需要注意的是，无论是否抛出异常，finally子句都会执行。

另外，在finally子句中返回的值往往会覆盖try代码块中返回的值，对于finally从句中抛出的异常也会覆盖try中所抛出的异常。

```java
class VeryImportantException extends Exception {
    public String toString() {
        return "A very important exception!";
    }
}
class HoHumException extends Exception {
    public String toString() {
        return "A trivial exception";
    }
}
public class LostMessage {
    void f() throws VeryImportantException {
        throw new VeryImportantException();
    }
    void dispose() throws HoHumException {
        throw new HoHumException();
    }
    public static void main(String[] args) throws Exception {
        LostMessage lm = new LostMessage();
        try {
            lm.f();
        } finally {
            lm.dispose();
        }
    }
}
```

